// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DailyPlanet_IOS
{
	public partial class itemViewController : UIViewController
	{
		public itemViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
